version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db_container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=data_engineering
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: